[opener]

edit = [
  { run = 'helix "$@"', block = true, desc = "Helix", for = "unix" },
  { run = 'code "$@"', orphan = true, desc = "VS Code", for = "windows" },
  { run = 'code -w "$@"', block = true, desc = "VS Code (block)", for = "windows" },
]

open = [
  { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
  { run = 'open "$@"', desc = "Open", for = "macos" },
  { run = 'start "" "$@"', orphan = true, desc = "Open", for = "windows" },
  { run = 'termux-open "$@"', desc = "Open", for = "android" },
]

reveal = [
  { run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" },
  { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
  { run = 'explorer /select,"$1"', orphan = true, desc = "Reveal", for = "windows" },
  { run = 'termux-open "$(dirname "$1")"', desc = "Reveal", for = "android" },
  { run = '''clear; exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]

extract = [
  { run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
  { run = 'ya pub extract --list "$@"', desc = "Extract here", for = "windows" },
]

play = [
  { run = 'mpv --force-window "$@"', orphan = true, desc = "Play", for = "unix" },
  { run = 'mpv --force-window "$@"', orphan = true, desc = "Play", for = "windows" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

